In [ ]:
%matplotlib inline

In [38]:
import subhalo_selection 
reload(subhalo_selection)



host_halo_occupations = np.array((1, 2, 0, 1, 0))
host_halo_binning_property = np.array((0.5, 1.5, 0.5, 3.5, 4.5))
satellite_host_property = np.repeat(host_halo_binning_property, host_halo_occupations)
bin_edges = np.array((0, 1, 2., 3., 4, 5))

num_subhalos = int(1e3)
sorted_subhalo_binning_property = np.sort(np.random.uniform(0.01, 3.99, num_subhalos))

result = subhalo_selection.select_subhalo_indices(host_halo_occupations, 
                                                  satellite_host_property,
                            bin_edges, sorted_subhalo_binning_property)


result

array([ 55, 309, 378, 895])

In [36]:
sorted_subhalo_binning_property = np.array((0.5, 1., 1.5, 1.5, 2.5))
bin_edges = np.array((0, 1, 2., 3.))

# np.digitize(sorted_subhalo_binning_property, bin_edges) - 1


In [ ]:
np.searchsorted(bin_edges, sorted_subhalo_binning_property) - 1

In [ ]:
%load_ext Cython

In [ ]:
%%cython 

cimport cython
from libc.stdlib cimport rand, RAND_MAX
from libc.math cimport floor
import numpy as np

cdef double random_uniform():
    cdef double r = rand()
    return r / RAND_MAX

@cython.boundscheck(False)
@cython.wraparound(False)
@cython.nonecheck(False)
def subhalo_index_kernel(long[:] satellite_bin_indices, long[:] subhalo_bin_indices):
    """
    Parameters
    ----------
    satellite_bin_indices : ndarray
        Array of long integers of shape (num_sats, ) storing the host halo mass bin of
        every satellite galaxy in the mock.
        All values must be between 0 and num_bins - 2, inclusive

    subhalo_bin_indices : ndarray
        Array of long integers of shape (num_bins, ) storing the first index
        where a subhalo belongs in the next host mass bin

    Returns
    -------
    subhalo_indices : ndarray
        Array of long integers of shape (num_sats, ) that can be used
        as an indexing array into subhalos
    """
    cdef int num_draws = len(satellite_bin_indices)
    cdef int i, bin_index
    cdef double u
    cdef long low, high
    cdef long[:] result = np.zeros(num_draws).astype('i8')

    for i in range(num_draws):
        bin_index = satellite_bin_indices[i]
        low = subhalo_bin_indices[bin_index]
        high = subhalo_bin_indices[bin_index+1]
        u = random_uniform()
        result[i] = <long>floor(u*(high-low) + low)
    return result





In [ ]:
satellite_bin_indices = np.array([0, 0])

subhalo_bin_indices = np.array([0, 4, 9])

np.array(subhalo_index_kernel(satellite_bin_indices, subhalo_bin_indices))

In [ ]:
from random import random
from math import floor 

for i in range(16):
    low, high = 3, 5
    u = random()
    print(int(floor(u*(high-low) + low)))

In [48]:
np.random.randint([0, 0, 0], [4, 4, 4], 3)

ValueError: high is out of bounds for int64

In [51]:
np.random.uniform((0, 0, 0), (1, 2, 3), 3)

array([ 0.28507816,  0.72802567,  0.35435714])

In [54]:
np.floor(u*(high-low) + low)

In [93]:

low = np.array((0, 3, 8, 3))
high = np.array((3, 8, 12, 8))
num_sats = len(low)

indices = (np.floor(np.random.rand(num_sats)*(high - low) + low)).astype('i8')
indices

array([ 2,  3, 11,  5])

In [96]:
np.searchsorted((0, 1, 2), 0.5)

1